// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CheckDependencies():Promise<main.DependencyStatus>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClearHistory():Promise<void>;

export function DeleteHistoryEntry(arg1:string):Promise<void>;

export function DownloadDependencies():Promise<void>;

export function FetchMetadata(arg1:string):Promise<main.VideoMetadata>;

export function GetAppVersion():Promise<string>;

export function GetFfmpegVersion():Promise<string>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function GetSettings():Promise<main.Settings>;

export function GetVersionInfo():Promise<main.VersionInfo>;

export function GetYtdlpVersion():Promise<string>;

export function IsBrowserRunning(arg1:string):Promise<boolean>;

export function KillBrowser(arg1:string):Promise<void>;

export function OpenBinDir():Promise<void>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function OpenOutputDir(arg1:string):Promise<void>;

export function SelectCookieFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFfmpegPath():Promise<string>;

export function StartDownload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function StartDownloadWithPreset(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function UpdateDependencies():Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;

export function PlayFile(arg1:string):Promise<void>;

export function ShowFileInFolder(arg1:string):Promise<void>;
