// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function DownloadDependencies() {
  return window['go']['main']['App']['DownloadDependencies']();
}

export function FetchMetadata(arg1) {
  return window['go']['main']['App']['FetchMetadata'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetYtdlpVersion() {
  return window['go']['main']['App']['GetYtdlpVersion']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
