// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CheckDependencies():Promise<main.DependencyStatus>;

export function DownloadDependencies():Promise<void>;

export function FetchMetadata(arg1:string):Promise<main.VideoMetadata>;

export function GetSettings():Promise<main.Settings>;

export function GetYtdlpVersion():Promise<string>;

export function SelectDirectory():Promise<string>;

export function StartDownload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
