// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function DownloadDependencies() {
  return window['go']['main']['App']['DownloadDependencies']();
}

export function FetchMetadata(arg1) {
  return window['go']['main']['App']['FetchMetadata'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetFfmpegVersion() {
  return window['go']['main']['App']['GetFfmpegVersion']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function GetYtdlpVersion() {
  return window['go']['main']['App']['GetYtdlpVersion']();
}

export function IsBrowserRunning(arg1) {
  return window['go']['main']['App']['IsBrowserRunning'](arg1);
}

export function KillBrowser(arg1) {
  return window['go']['main']['App']['KillBrowser'](arg1);
}

export function OpenBinDir() {
  return window['go']['main']['App']['OpenBinDir']();
}

export function OpenExternalLink(arg1) {
  return window['go']['main']['App']['OpenExternalLink'](arg1);
}

export function OpenOutputDir(arg1) {
  return window['go']['main']['App']['OpenOutputDir'](arg1);
}

export function PlayFile(arg1) {
  return window['go']['main']['App']['PlayFile'](arg1);
}

export function SelectCookieFile() {
  return window['go']['main']['App']['SelectCookieFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFfmpegPath() {
  return window['go']['main']['App']['SelectFfmpegPath']();
}

export function ShowFileInFolder(arg1) {
  return window['go']['main']['App']['ShowFileInFolder'](arg1);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartDownloadWithPreset(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['StartDownloadWithPreset'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateDependencies() {
  return window['go']['main']['App']['UpdateDependencies']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
